/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;


import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.Timer;

/**
 *
 * @author Carl
 */
public class LobbyChar extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form Creditos
     */
    public LobbyChar() {
        initComponents();
        int watts = 0;
        int tiempo = 0;
        int relacion = 0;
        
        t = new Timer(10,acciones);
        
    }
    //Cronometro
    private Timer t;
    private int h,m,s,cs;
    
    private ActionListener acciones = new ActionListener(){
        
        
    @Override 
        public void actionPerformed(ActionEvent ae){
            cs++;
            if(cs==100){
                cs = 0;
                ++s;
                
            }
            if(s==60){
                s=0;
                ++m;
            }
            if(m==60){
                m =0;
                ++h;
            }
            actualizarLabel();
        }
    };
    
    private void actualizarLabel(){
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
        etiquetaTiempo.setText(tiempo);
    }
    
    private void actualizarPuntos(){
        
        String puntosrelacion = "0";
        int puntos = 0;
        Relacion.setText(puntosrelacion);
    }
    
    public void inicioCount(){
        t.start();
    }
    
    
    
    
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Creditos = new javax.swing.JButton();
        Charmeleon = new javax.swing.JLabel();
        Relacion = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        TiempoJugado = new javax.swing.JLabel();
        Relacionint = new javax.swing.JLabel();
        Tienda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        Creditos.setText("Back to Menu");
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });

        Charmeleon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Charmeleon.setForeground(new java.awt.Color(255, 255, 255));
        Charmeleon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Movimientos Charmeleon/Normal-removebg-preview.png"))); // NOI18N

        Relacion.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Relacion.setForeground(new java.awt.Color(255, 255, 255));
        Relacion.setText("Relación:");
        Relacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RelacionMouseClicked(evt);
            }
        });

        etiquetaTiempo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaTiempo.setText("00:00:00:00");

        TiempoJugado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TiempoJugado.setForeground(new java.awt.Color(255, 255, 255));
        TiempoJugado.setText("Tiempo jugado");
        TiempoJugado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiempoJugadoMouseClicked(evt);
            }
        });

        Relacionint.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Relacionint.setForeground(new java.awt.Color(255, 255, 255));
        Relacionint.setText("0");
        Relacionint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RelacionintMouseClicked(evt);
            }
        });

        Tienda.setText("Tienda");
        Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Creditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TiempoJugado)
                        .addGap(18, 18, 18)))
                .addComponent(etiquetaTiempo)
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Relacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Relacionint)
                        .addGap(256, 256, 256)
                        .addComponent(Tienda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(Charmeleon)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Creditos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TiempoJugado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(Charmeleon)
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relacion)
                    .addComponent(Relacionint)
                    .addComponent(Tienda))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed
        
        t.stop();
        try {
            // Ir al menu
            Menu j = new Menu();
            j.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(LobbyChar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(LobbyChar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreditosActionPerformed

    private void RelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RelacionMouseClicked

    private void TiempoJugadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiempoJugadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoJugadoMouseClicked

    private void RelacionintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelacionintMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RelacionintMouseClicked

    private void TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiendaActionPerformed
        // Abre la tienda:
            TiendaBayas tiendita = new TiendaBayas();
            tiendita.setVisible(true);
            
            
    }//GEN-LAST:event_TiendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Charmeleon;
    private javax.swing.JButton Creditos;
    private javax.swing.JLabel Relacion;
    private javax.swing.JLabel Relacionint;
    private javax.swing.JLabel TiempoJugado;
    private javax.swing.JButton Tienda;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
